name: vision05
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.1
  - opencv=4.9.0
  - py-opencv=4.9.0
  - yad=13.0
  - face-recognition=1.3.0
  - pygobject=3.46.0
  - gtk3=3.24.41